	spring.application.name=JobListingProject
	
	spring.data.mongodb.uri=mongodb+srv://root:SCOUT07@cluster0.nggcqpm.mongodb.net/Rohan?retryWrites=true&w=majority
	
	
	
	spring.data.mongodb.database=Rohan
